AWSTemplateFormatVersion: '2010-09-09'
Description: 'Image Classification

  '
Globals:
  Function:
    Timeout: 10
Resources:
  RecognizeFunction:
    Properties:
      CodeUri: s3://fdingler-sam-artifacts/393063cb5981da2c4c9ff2be14f3eead
      Events:
        API:
          Properties:
            Method: post
            Path: /recognize
          Type: Api
      Handler: app.handler
      Policies:
      - AmazonSageMakerFullAccess
      - AWSXrayFullAccess
      Runtime: nodejs8.10
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
