AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Image Classification

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 10

Resources:
  RecognizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: recognize.handler
      Policies:
        - AmazonSageMakerFullAccess
        - AWSXrayFullAccess
      Tracing: Active
      Environment:
        Variables:
          SAGE_MAKER_ENDPOINT: 'mantis-image-classification-endpoint'
          DOCKER_ENDPOINT: 'http://ec2-54-201-97-15.us-west-2.compute.amazonaws.com/predictions/resnet'
          # USE_SAGE_MAKER: true
      Events:
        API:
          Type: Api
          Properties:
            Path: /recognize
            Method: post

  StopEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: cron.stopEndpoint
      Timeout: 60
      Policies:
      - AmazonSageMakerFullAccess
      Environment:
        Variables:
          SAGE_MAKER_ENDPOINT: 'mantis-image-classification-endpoint'
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 7 * * ? *)

  StartEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: cron.startEndpoint
      Timeout: 60
      Policies:
      - AmazonSageMakerFullAccess
      Environment:
        Variables:
          SAGE_MAKER_ENDPOINT: 'mantis-image-classification-endpoint'
          SAGE_MAKER_ENDPOINT_CONFIG: 'mantis-image-classification-endpoint-configuration-v2'
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 15 * * ? *)
